version: '3.8'

services:
  api:
    container_name: technical-test-api
    build:
      context: .
    restart: unless-stopped
    command: >
      sh -c "alembic upgrade head && uvicorn main:app --reload --host 0.0.0.0 --port 8000"
    ports:
      - 8000:8000
    volumes:
      - ./app:/app
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:16-alpine
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'"]
      interval: 2s
      timeout: 30s
      retries: 10

volumes:
  postgres-data:
